# Generated by Django 4.1.7 on 2023-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_name', models.CharField(blank=True, max_length=50)),
                ('owners_name', models.CharField(blank=True, max_length=50)),
                ('units', models.IntegerField(blank=True)),
            ],
        ),
    ]
